run:
  concurrency: 4
  deadline: 3m
  tests: true
  modules-download-mode: vendor
  #skip-dirs # vendor & generated files are skipped by default

output:
  format: tab
  print-issued-lines: true
  print-linter-name: true
  sort-results: false

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - godot
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
    - wsl
  fast: false

linters-settings:
  cyclop:
    max-complexity: 18
  errcheck:
    check-type-assertions: true
  exhaustive:
    default-signifies-exhaustive: true
  gocognit:
    min-complexity: 18
  gofumpt:
    lang-version: '1.16'
  goimports:
    local-prefixes: code.tooling.prod.cdsf.io/ctp
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: UK
  lll:
    line-length: 160
  staticcheck:
    # Select the Go version to target. The default is '1.13'.
    go: '1.16'
  stylecheck:
    # Select the Go version to target. The default is '1.13'.
    go: '1.16'
  unused:
    # Select the Go version to target. The default is '1.13'.
    go: '1.16'

